version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/mini3-server
    overwrite: yes

permissions:
  - object: /home/ubuntu/mini3-server
    pattern: "*"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/gh_deploy.sh
      timeout: 60
      runas: ubuntu