version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/mini3-server

permissions:
  - object: /home/ec2-user/mini3-server
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: scripts/gh_deploy.sh
      timeout: 60
      runas: ec2-user