  spring:
    redis:
      host: localhost
      port: 6379
    datasource:
      url: jdbc:h2:mem:test;MODE=MySQL
      driver-class-name: org.h2.Driver
      username: sa
      password:
    h2:
      console:
        enabled: true
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
          jdbc:
            time_zone: Asia/Seoul
        default_batch_fetch_size: 100
      open-in-view: false
  file:
    path: "./images/"
  secret-key: klner8xv0se